defmodule JidoClaw.Repo.Migrations.CreateSecuritySecretRefs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:secret_refs, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:category, :text, null: false, default: "general")
      add(:user_id, :uuid, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:encrypted_encrypted_value, :binary, null: false)
    end

    create(
      unique_index(:secret_refs, [:name, :user_id],
        name: "secret_refs_unique_name_per_user_index"
      )
    )
  end

  def down do
    drop_if_exists(
      unique_index(:secret_refs, [:name, :user_id],
        name: "secret_refs_unique_name_per_user_index"
      )
    )

    drop(table(:secret_refs))
  end
end
