defmodule JidoClaw.Repo.Migrations.CreateFolioTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:folio_projects, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:outcome, :text)
      add(:notes, :text)
      add(:status, :text, null: false, default: "active")
      add(:user_id, :uuid)
      add(:completed_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:folio_inbox_items, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:title, :text, null: false)
      add(:notes, :text)
      add(:source, :text, default: "manual")
      add(:status, :text, null: false, default: "inbox")
      add(:user_id, :uuid)
      add(:processed_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:folio_actions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:title, :text, null: false)
      add(:notes, :text)
      add(:context, :text)
      add(:energy, :text)
      add(:time_estimate, :bigint)
      add(:status, :text, null: false, default: "next")
      add(:waiting_for, :text)
      add(:due_date, :date)
      add(:project_id, :uuid)
      add(:user_id, :uuid)
      add(:completed_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    drop(table(:folio_actions))

    drop(table(:folio_inbox_items))

    drop(table(:folio_projects))
  end
end
