defmodule JidoClaw.Repo.Migrations.CreateGithubIssueAnalyses do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:github_issue_analyses, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:issue_number, :bigint, null: false)
      add(:repo_full_name, :text, null: false)
      add(:classification, :text)
      add(:confidence, :float)
      add(:status, :text, null: false, default: "pending")
      add(:triage_data, :map, default: %{})
      add(:research_data, :map, default: %{})
      add(:pr_data, :map, default: %{})
      add(:project_id, :uuid)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    drop(table(:github_issue_analyses))
  end
end
